spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ems_db

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none

jwt.secret=QU4yZQ+YzoDJ1b3SJUnuOxOqFncnPSgjmJoYudxeyLXqiKb9OfgMA16uhQKQEIVN60iBjui7tI1TS6OmIT0/1w==
#jwt.secret=${JWT_SECRET}
jwt.expiration=3600000